// Code generated by go-bindata.
// sources:
// server/data/config/config.yml
// server/data/static/build/bundle.css
// server/data/static/build/bundle.js
// server/data/static/build/glyphicons-halflings-regular-89889688147bd7575d6327160d64e760.svg
// server/data/static/build/glyphicons-halflings-regular-e18bbf611f2a2e43afc071aa2f4e1512.ttf
// server/data/static/build/glyphicons-halflings-regular@39add9c7a1f4a4518e3df09c8cea5a7d.eot
// server/data/static/build/glyphicons-halflings-regular@9d6e95fb59f8df43b8fac50a249fa351.ttf
// server/data/static/build/glyphicons-halflings-regular@aab920e04211577da140c01f1f39adff.woff
// server/data/static/images/favicon.ico
// server/data/static/images/identity/.DS_Store
// server/data/static/images/identity/logo-lg.png
// server/data/static/images/identity/logo-md.png
// server/data/static/images/identity/logo-sm.png
// server/data/static/images/identity/logo-tiny.png
// server/data/static/images/identity/logo-white-lg.png
// server/data/static/images/identity/logo-white-md.png
// server/data/static/images/identity/logo-white-sm.png
// server/data/static/images/identity/logo-white-tiny.png
// server/data/static/images/identity/logo-white-xl.png
// server/data/static/images/identity/logo-white-xs.png
// server/data/static/images/identity/logo-xl.png
// server/data/static/images/identity/logo-xs.png
// server/data/static/images/logo-lg.png
// server/data/templates/react.html
// DO NOT EDIT!

package assets

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// configConfigYml reads file data from disk. It returns an error on failure.
func configConfigYml() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/config/config.yml"
	name := "config/config.yml"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticBuildBundleCss reads file data from disk. It returns an error on failure.
func staticBuildBundleCss() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/build/bundle.css"
	name := "static/build/bundle.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticBuildBundleJs reads file data from disk. It returns an error on failure.
func staticBuildBundleJs() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/build/bundle.js"
	name := "static/build/bundle.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticBuildGlyphiconsHalflingsRegular89889688147bd7575d6327160d64e760Svg reads file data from disk. It returns an error on failure.
func staticBuildGlyphiconsHalflingsRegular89889688147bd7575d6327160d64e760Svg() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/build/glyphicons-halflings-regular-89889688147bd7575d6327160d64e760.svg"
	name := "static/build/glyphicons-halflings-regular-89889688147bd7575d6327160d64e760.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticBuildGlyphiconsHalflingsRegularE18bbf611f2a2e43afc071aa2f4e1512Ttf reads file data from disk. It returns an error on failure.
func staticBuildGlyphiconsHalflingsRegularE18bbf611f2a2e43afc071aa2f4e1512Ttf() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/build/glyphicons-halflings-regular-e18bbf611f2a2e43afc071aa2f4e1512.ttf"
	name := "static/build/glyphicons-halflings-regular-e18bbf611f2a2e43afc071aa2f4e1512.ttf"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticBuildGlyphiconsHalflingsRegular39add9c7a1f4a4518e3df09c8cea5a7dEot reads file data from disk. It returns an error on failure.
func staticBuildGlyphiconsHalflingsRegular39add9c7a1f4a4518e3df09c8cea5a7dEot() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/build/glyphicons-halflings-regular@39add9c7a1f4a4518e3df09c8cea5a7d.eot"
	name := "static/build/glyphicons-halflings-regular@39add9c7a1f4a4518e3df09c8cea5a7d.eot"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticBuildGlyphiconsHalflingsRegular9d6e95fb59f8df43b8fac50a249fa351Ttf reads file data from disk. It returns an error on failure.
func staticBuildGlyphiconsHalflingsRegular9d6e95fb59f8df43b8fac50a249fa351Ttf() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/build/glyphicons-halflings-regular@9d6e95fb59f8df43b8fac50a249fa351.ttf"
	name := "static/build/glyphicons-halflings-regular@9d6e95fb59f8df43b8fac50a249fa351.ttf"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticBuildGlyphiconsHalflingsRegularAab920e04211577da140c01f1f39adffWoff reads file data from disk. It returns an error on failure.
func staticBuildGlyphiconsHalflingsRegularAab920e04211577da140c01f1f39adffWoff() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/build/glyphicons-halflings-regular@aab920e04211577da140c01f1f39adff.woff"
	name := "static/build/glyphicons-halflings-regular@aab920e04211577da140c01f1f39adff.woff"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticImagesFaviconIco reads file data from disk. It returns an error on failure.
func staticImagesFaviconIco() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/images/favicon.ico"
	name := "static/images/favicon.ico"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticImagesIdentityDs_store reads file data from disk. It returns an error on failure.
func staticImagesIdentityDs_store() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/images/identity/.DS_Store"
	name := "static/images/identity/.DS_Store"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticImagesIdentityLogoLgPng reads file data from disk. It returns an error on failure.
func staticImagesIdentityLogoLgPng() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/images/identity/logo-lg.png"
	name := "static/images/identity/logo-lg.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticImagesIdentityLogoMdPng reads file data from disk. It returns an error on failure.
func staticImagesIdentityLogoMdPng() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/images/identity/logo-md.png"
	name := "static/images/identity/logo-md.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticImagesIdentityLogoSmPng reads file data from disk. It returns an error on failure.
func staticImagesIdentityLogoSmPng() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/images/identity/logo-sm.png"
	name := "static/images/identity/logo-sm.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticImagesIdentityLogoTinyPng reads file data from disk. It returns an error on failure.
func staticImagesIdentityLogoTinyPng() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/images/identity/logo-tiny.png"
	name := "static/images/identity/logo-tiny.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticImagesIdentityLogoWhiteLgPng reads file data from disk. It returns an error on failure.
func staticImagesIdentityLogoWhiteLgPng() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/images/identity/logo-white-lg.png"
	name := "static/images/identity/logo-white-lg.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticImagesIdentityLogoWhiteMdPng reads file data from disk. It returns an error on failure.
func staticImagesIdentityLogoWhiteMdPng() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/images/identity/logo-white-md.png"
	name := "static/images/identity/logo-white-md.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticImagesIdentityLogoWhiteSmPng reads file data from disk. It returns an error on failure.
func staticImagesIdentityLogoWhiteSmPng() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/images/identity/logo-white-sm.png"
	name := "static/images/identity/logo-white-sm.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticImagesIdentityLogoWhiteTinyPng reads file data from disk. It returns an error on failure.
func staticImagesIdentityLogoWhiteTinyPng() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/images/identity/logo-white-tiny.png"
	name := "static/images/identity/logo-white-tiny.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticImagesIdentityLogoWhiteXlPng reads file data from disk. It returns an error on failure.
func staticImagesIdentityLogoWhiteXlPng() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/images/identity/logo-white-xl.png"
	name := "static/images/identity/logo-white-xl.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticImagesIdentityLogoWhiteXsPng reads file data from disk. It returns an error on failure.
func staticImagesIdentityLogoWhiteXsPng() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/images/identity/logo-white-xs.png"
	name := "static/images/identity/logo-white-xs.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticImagesIdentityLogoXlPng reads file data from disk. It returns an error on failure.
func staticImagesIdentityLogoXlPng() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/images/identity/logo-xl.png"
	name := "static/images/identity/logo-xl.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticImagesIdentityLogoXsPng reads file data from disk. It returns an error on failure.
func staticImagesIdentityLogoXsPng() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/images/identity/logo-xs.png"
	name := "static/images/identity/logo-xs.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticImagesLogoLgPng reads file data from disk. It returns an error on failure.
func staticImagesLogoLgPng() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/static/images/logo-lg.png"
	name := "static/images/logo-lg.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templatesReactHtml reads file data from disk. It returns an error on failure.
func templatesReactHtml() (*asset, error) {
	path := "/Users/konrad/Projects/Go/src/github.com/iKonrad/typitap/server/data/templates/react.html"
	name := "templates/react.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"config/config.yml": configConfigYml,
	"static/build/bundle.css": staticBuildBundleCss,
	"static/build/bundle.js": staticBuildBundleJs,
	"static/build/glyphicons-halflings-regular-89889688147bd7575d6327160d64e760.svg": staticBuildGlyphiconsHalflingsRegular89889688147bd7575d6327160d64e760Svg,
	"static/build/glyphicons-halflings-regular-e18bbf611f2a2e43afc071aa2f4e1512.ttf": staticBuildGlyphiconsHalflingsRegularE18bbf611f2a2e43afc071aa2f4e1512Ttf,
	"static/build/glyphicons-halflings-regular@39add9c7a1f4a4518e3df09c8cea5a7d.eot": staticBuildGlyphiconsHalflingsRegular39add9c7a1f4a4518e3df09c8cea5a7dEot,
	"static/build/glyphicons-halflings-regular@9d6e95fb59f8df43b8fac50a249fa351.ttf": staticBuildGlyphiconsHalflingsRegular9d6e95fb59f8df43b8fac50a249fa351Ttf,
	"static/build/glyphicons-halflings-regular@aab920e04211577da140c01f1f39adff.woff": staticBuildGlyphiconsHalflingsRegularAab920e04211577da140c01f1f39adffWoff,
	"static/images/favicon.ico": staticImagesFaviconIco,
	"static/images/identity/.DS_Store": staticImagesIdentityDs_store,
	"static/images/identity/logo-lg.png": staticImagesIdentityLogoLgPng,
	"static/images/identity/logo-md.png": staticImagesIdentityLogoMdPng,
	"static/images/identity/logo-sm.png": staticImagesIdentityLogoSmPng,
	"static/images/identity/logo-tiny.png": staticImagesIdentityLogoTinyPng,
	"static/images/identity/logo-white-lg.png": staticImagesIdentityLogoWhiteLgPng,
	"static/images/identity/logo-white-md.png": staticImagesIdentityLogoWhiteMdPng,
	"static/images/identity/logo-white-sm.png": staticImagesIdentityLogoWhiteSmPng,
	"static/images/identity/logo-white-tiny.png": staticImagesIdentityLogoWhiteTinyPng,
	"static/images/identity/logo-white-xl.png": staticImagesIdentityLogoWhiteXlPng,
	"static/images/identity/logo-white-xs.png": staticImagesIdentityLogoWhiteXsPng,
	"static/images/identity/logo-xl.png": staticImagesIdentityLogoXlPng,
	"static/images/identity/logo-xs.png": staticImagesIdentityLogoXsPng,
	"static/images/logo-lg.png": staticImagesLogoLgPng,
	"templates/react.html": templatesReactHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"config": &bintree{nil, map[string]*bintree{
		"config.yml": &bintree{configConfigYml, map[string]*bintree{}},
	}},
	"static": &bintree{nil, map[string]*bintree{
		"build": &bintree{nil, map[string]*bintree{
			"bundle.css": &bintree{staticBuildBundleCss, map[string]*bintree{}},
			"bundle.js": &bintree{staticBuildBundleJs, map[string]*bintree{}},
			"glyphicons-halflings-regular-89889688147bd7575d6327160d64e760.svg": &bintree{staticBuildGlyphiconsHalflingsRegular89889688147bd7575d6327160d64e760Svg, map[string]*bintree{}},
			"glyphicons-halflings-regular-e18bbf611f2a2e43afc071aa2f4e1512.ttf": &bintree{staticBuildGlyphiconsHalflingsRegularE18bbf611f2a2e43afc071aa2f4e1512Ttf, map[string]*bintree{}},
			"glyphicons-halflings-regular@39add9c7a1f4a4518e3df09c8cea5a7d.eot": &bintree{staticBuildGlyphiconsHalflingsRegular39add9c7a1f4a4518e3df09c8cea5a7dEot, map[string]*bintree{}},
			"glyphicons-halflings-regular@9d6e95fb59f8df43b8fac50a249fa351.ttf": &bintree{staticBuildGlyphiconsHalflingsRegular9d6e95fb59f8df43b8fac50a249fa351Ttf, map[string]*bintree{}},
			"glyphicons-halflings-regular@aab920e04211577da140c01f1f39adff.woff": &bintree{staticBuildGlyphiconsHalflingsRegularAab920e04211577da140c01f1f39adffWoff, map[string]*bintree{}},
		}},
		"images": &bintree{nil, map[string]*bintree{
			"favicon.ico": &bintree{staticImagesFaviconIco, map[string]*bintree{}},
			"identity": &bintree{nil, map[string]*bintree{
				".DS_Store": &bintree{staticImagesIdentityDs_store, map[string]*bintree{}},
				"logo-lg.png": &bintree{staticImagesIdentityLogoLgPng, map[string]*bintree{}},
				"logo-md.png": &bintree{staticImagesIdentityLogoMdPng, map[string]*bintree{}},
				"logo-sm.png": &bintree{staticImagesIdentityLogoSmPng, map[string]*bintree{}},
				"logo-tiny.png": &bintree{staticImagesIdentityLogoTinyPng, map[string]*bintree{}},
				"logo-white-lg.png": &bintree{staticImagesIdentityLogoWhiteLgPng, map[string]*bintree{}},
				"logo-white-md.png": &bintree{staticImagesIdentityLogoWhiteMdPng, map[string]*bintree{}},
				"logo-white-sm.png": &bintree{staticImagesIdentityLogoWhiteSmPng, map[string]*bintree{}},
				"logo-white-tiny.png": &bintree{staticImagesIdentityLogoWhiteTinyPng, map[string]*bintree{}},
				"logo-white-xl.png": &bintree{staticImagesIdentityLogoWhiteXlPng, map[string]*bintree{}},
				"logo-white-xs.png": &bintree{staticImagesIdentityLogoWhiteXsPng, map[string]*bintree{}},
				"logo-xl.png": &bintree{staticImagesIdentityLogoXlPng, map[string]*bintree{}},
				"logo-xs.png": &bintree{staticImagesIdentityLogoXsPng, map[string]*bintree{}},
			}},
			"logo-lg.png": &bintree{staticImagesLogoLgPng, map[string]*bintree{}},
		}},
	}},
	"templates": &bintree{nil, map[string]*bintree{
		"react.html": &bintree{templatesReactHtml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

