const Constants = {
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
    ACTIVATE_USER_SUCCESS: "ACTIVATE_USER_SUCCESS",
    ACTIVATE_USER_FAILURE: "ACTIVATE_USER_FAILURE",
};

export default Constants;